### ISSUE TITLE
lag when the preview is open

### ISSUE THREAD

**Issue by jwverzijden** [benderTheCrime/jsdoc-preview#3]
I notice significant lag in any editor window when the preview window is open.

**Comment by benderTheCrime** [comment]
Do you have any more specific information? This is a form of the markdown-preview atom package and uses jsdoc via jsdoc-markdown to generate. There's not a whole lot going on that's special or specific to this package. It scrubs links and queries for the main body of the generated jsdoc DOM.

**Comment by benderTheCrime** [comment]
*fork

**Comment by jwverzijden** [comment]
well first i thought i may have hit a point where the collective of packages is causing this delay..
so i started turning off packages untill it was gone.. but it seems only turning this one off helped.. so i dont know what its made of and if its even posible.. but i dare say that this package definetly makes my editor unusable.

**Comment by benderTheCrime** [comment]
I'm sorry, maybe my reasoning for closing this earlier was not very clear:

I know very well that this package does a lot of work due to the fact that it is parsing JSDocs, generating html from JSDocs, selecting and filtering DOM elements on the fly, and updating on change. It does not have to be used to update on change, but that is available for people who would like to do so. 

Regardless of the fact that this should somehow be reflected in the CONTRIBUTING.md or in the issue template, I would prefer that issues made on this repository reflect a specific way to improve the performance of the plugin, or come in the form of an actual pull request, rather than just reporting blanket performance issues.
